name: Tag & Build

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - "**/.gitignore"
      - "**/.vscode/**"
      - "**/README.md"
      - "**/CHANGELOG.md"
      - "**/docs/**"
  pull_request:
    branches:
      - main
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  tag:
    runs-on: ubuntu-latest
    if: (github.ref_name == 'main' || github.ref_name == 'dev') && github.event_name == 'push'
    permissions:
      contents: write # for the tags
    outputs:
      version: ${{ steps.git_version.outputs.version }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-tags: true
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: setup git
        run: |
          git config --local user.email "pewdiepie-archdaemon@users.noreply.github.com"
          git config --local user.name "Odysseus Bot"

      - name: set version format
        id: version_format
        run: |
          if [[ ${{ github.ref_name }} == 'main' ]]; then
            echo "version_format=\${major}.\${minor}.\${patch}" >> $GITHUB_OUTPUT
          else
            echo "version_format=\${major}.\${minor}.\${patch}rc\${increment}" >> $GITHUB_OUTPUT
          fi

      - name: Git Version
        uses: PaulHatch/semantic-version@a8f8f59fd7f0625188492e945240f12d7ad2dca3  # v5.4.0
        id: git_version
        with:
          tag_prefix: ""
          major_pattern: "breaking:"
          minor_pattern: "feat:"
          enable_prerelease_mode: false
          version_format: ${{ steps.version_format.outputs.version_format }}
  
      - name: Create & Push Tag
        env:
          VERSION: ${{ steps.git_version.outputs.version }}
        run: |
          git tag "$VERSION"
          git push origin "$VERSION"

  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.event_name == 'push'
    needs: tag

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Log in to the Container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5.9.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ needs.tag.outputs.version }}
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
